/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cifrado;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valer
 */
public class interfaz2 extends javax.swing.JFrame {

    private ArrayList<Byte> byteList = new ArrayList<>();
    private int totalBytes = 0;//El total de bytes del archivo abierto
    String ruta;//La ruta del archivo abierto
    String[] columnNames = {"#", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};//Titulo de las columnas de ambas tablas
    MostrarArchivo abrir = new MostrarArchivo(); // Se necesita que los metodos sean globales del archivo analizado
    File archivo;//Se necesita el archivo global
    ComportamientoDeTablas inicializarcomportamientoarchivo,
            inicializarcomportamientocifrado,
            inicializarcomportamientodescifrado,
            inicializarcomportamientodehash; //Inicializa comportamiento de mostrar bytes del archivo
    OperacionesCifradosHash metodosarchivo = new OperacionesCifradosHash(); //Clase donde todo se puede para cifrar el archivo 
    //Lo subi principalmente para descifrado 
    MostrarArchivo archivonormal = new MostrarArchivo();//Usar los metodos para que pueda usar los bytes que se han mostrado 
    MostrarArchivo archivonormalhash = new MostrarArchivo();//Usar los metodos para que pueda usar los bytes que se han mostrado 

    /**
     * Creates new form interfaz2
     */
    public interfaz2() {
        Tablas tabla= new Tablas();
        initComponents();
        //COMPORTAMIENTO TABLAS ARCHIVO
        inicializarcomportamientoarchivo = new ComportamientoDeTablas(tableASCII,
                tableHex,
                spinnerSeleccion,
                txtAsciiValue,
                txtHexValue,
                columnNames);

        inicializarcomportamientoarchivo.initListeners();
        inicializarcomportamientoarchivo.configurarTablas();  // Configura títulos y bloquea columnas
        inicializarcomportamientoarchivo.sincronizarColores();// Llamar a la función para sincronizar los colores
        //COMPORTAMIENTO TABLAS CIFRADO
        inicializarcomportamientocifrado = new ComportamientoDeTablas(tableASCII1,
                tableHex1,
                spinnerSeleccion1,
                txtAsciiValue1,
                txtHexValue1,
                columnNames);

        inicializarcomportamientocifrado.initListeners();
        inicializarcomportamientocifrado.configurarTablas();
        inicializarcomportamientocifrado.sincronizarColores();
        //COMPORTAMIENTO TABLAS DESCIFRADO
        inicializarcomportamientodescifrado = new ComportamientoDeTablas(tableASCII2,
                tableHex2,
                spinnerSeleccion2,
                txtAsciiValue2,
                txtHexValue2,
                columnNames);
        inicializarcomportamientodescifrado.initListeners();
        inicializarcomportamientodescifrado.configurarTablas();
        inicializarcomportamientodescifrado.sincronizarColores();

        //COMPORTAMIENTO TABLAS HASH
        inicializarcomportamientodehash = new ComportamientoDeTablas(
                tableASCII3,
                tableHex3,
                spinnerSeleccion3,
                txtAsciiValue3,
                txtHexValue3,
                columnNames);
        inicializarcomportamientodehash.initListeners();
        inicializarcomportamientodehash.configurarTablas();
        inicializarcomportamientodehash.sincronizarColores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        ScrollPanePrincipal = new javax.swing.JScrollPane();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        panelArchivoAbierto = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        PanelArchivo = new javax.swing.JPanel();
        panelArchivoOriginal = new javax.swing.JPanel();
        panelTablas = new javax.swing.JPanel();
        jPanelTables4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        spinnerSeleccion = new javax.swing.JSpinner();
        txtTotalBytes = new javax.swing.JTextField();
        txtAsciiValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHexValue = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnEditarArchivo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSplitPane6 = new javax.swing.JSplitPane();
        scrollPaneASCII = new javax.swing.JScrollPane();
        tableASCII = new javax.swing.JTable();
        scrollPaneHex = new javax.swing.JScrollPane();
        tableHex = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jTextFielddireccion = new javax.swing.JTextField();
        jButtonAbrir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelOperaciones = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Panel2 = new javax.swing.JPanel();
        panelTablasCifrar = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        scrollPaneASCII1 = new javax.swing.JScrollPane();
        tableASCII1 = new javax.swing.JTable();
        scrollPaneHex1 = new javax.swing.JScrollPane();
        tableHex1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelCifrar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        spinnerSeleccion1 = new javax.swing.JSpinner();
        txtTotalBytes1 = new javax.swing.JTextField();
        txtAsciiValue1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtHexValue1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCifrar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        panelDescifrado = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        spinnerSeleccion2 = new javax.swing.JSpinner();
        txtTotalBytes2 = new javax.swing.JTextField();
        txtAsciiValue2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtHexValue2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        btnDescifrar1 = new javax.swing.JButton();
        Guardar1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelTablasDescifrar = new javax.swing.JPanel();
        jSplitPaneDescifrar = new javax.swing.JSplitPane();
        scrollPaneASCII2 = new javax.swing.JScrollPane();
        tableASCII2 = new javax.swing.JTable();
        scrollPaneHex2 = new javax.swing.JScrollPane();
        tableHex2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        PanelTablasHash = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        scrollPaneASCII3 = new javax.swing.JScrollPane();
        tableASCII3 = new javax.swing.JTable();
        scrollPaneHex3 = new javax.swing.JScrollPane();
        tableHex3 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        panelHash = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        spinnerSeleccion3 = new javax.swing.JSpinner();
        txtTotalBytes3 = new javax.swing.JTextField();
        txtAsciiValue3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtHexValue3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        CalcularHash = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PanelBitacora = new javax.swing.JPanel();
        ScrollPaneBitacora = new javax.swing.JScrollPane();
        txtAreaBitacora = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        PanelPrincipal.setBackground(new java.awt.Color(236, 240, 241));
        PanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 15, true));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(950, 1431));

        jLabel20.setBackground(new java.awt.Color(204, 255, 255));
        jLabel20.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("SEGURIDAD WEB     \"CIFRADO Y DESCIFRADO\"");

        panelArchivoAbierto.setBackground(new java.awt.Color(0, 51, 153));
        panelArchivoAbierto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 10, true));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ARCHIVO ABIERTO");

        PanelArchivo.setBackground(new java.awt.Color(41, 128, 185));

        panelArchivoOriginal.setBackground(new java.awt.Color(52, 152, 219));

        panelTablas.setBackground(new java.awt.Color(236, 240, 241));

        jPanelTables4.setBackground(new java.awt.Color(255, 255, 204));
        jPanelTables4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setText("Posición ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("ASCII:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("HEX:");

        jLabel36.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel36.setText("/");

        btnEditarArchivo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnEditarArchivo.setForeground(new java.awt.Color(102, 0, 204));
        btnEditarArchivo.setText("EDITAR");
        btnEditarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalBytes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtAsciiValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHexValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinnerSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHexValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalBytes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtAsciiValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(btnEditarArchivo))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel17.setText("ASCII");

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel18.setText("HEXADECIMAL");

        jSplitPane6.setDividerLocation(337);

        tableASCII.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableASCII.setRowSelectionAllowed(false);
        tableASCII.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneASCII.setViewportView(tableASCII);

        jSplitPane6.setLeftComponent(scrollPaneASCII);

        tableHex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHex.setRowSelectionAllowed(false);
        tableHex.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneHex.setViewportView(tableHex);

        jSplitPane6.setRightComponent(scrollPaneHex);

        javax.swing.GroupLayout panelTablasLayout = new javax.swing.GroupLayout(panelTablas);
        panelTablas.setLayout(panelTablasLayout);
        panelTablasLayout.setHorizontalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablasLayout.createSequentialGroup()
                        .addComponent(jSplitPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTables4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        panelTablasLayout.setVerticalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGroup(panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanelTables4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSplitPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel19.setText("Archivo original ");

        javax.swing.GroupLayout panelArchivoOriginalLayout = new javax.swing.GroupLayout(panelArchivoOriginal);
        panelArchivoOriginal.setLayout(panelArchivoOriginalLayout);
        panelArchivoOriginalLayout.setHorizontalGroup(
            panelArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArchivoOriginalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );
        panelArchivoOriginalLayout.setVerticalGroup(
            panelArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArchivoOriginalLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAbrir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButtonAbrir.setForeground(new java.awt.Color(0, 0, 102));
        jButtonAbrir.setText("ABRIR ARCHIVO");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("ARCHIVO");

        javax.swing.GroupLayout PanelArchivoLayout = new javax.swing.GroupLayout(PanelArchivo);
        PanelArchivo.setLayout(PanelArchivoLayout);
        PanelArchivoLayout.setHorizontalGroup(
            PanelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArchivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArchivoLayout.createSequentialGroup()
                        .addComponent(panelArchivoOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArchivoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        PanelArchivoLayout.setVerticalGroup(
            PanelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArchivoLayout.createSequentialGroup()
                .addGroup(PanelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArchivoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(PanelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFielddireccion)
                            .addComponent(jLabel1)))
                    .addGroup(PanelArchivoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAbrir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArchivoOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelArchivoAbiertoLayout = new javax.swing.GroupLayout(panelArchivoAbierto);
        panelArchivoAbierto.setLayout(panelArchivoAbiertoLayout);
        panelArchivoAbiertoLayout.setHorizontalGroup(
            panelArchivoAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArchivoAbiertoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArchivoAbiertoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(309, 309, 309))
        );
        panelArchivoAbiertoLayout.setVerticalGroup(
            panelArchivoAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArchivoAbiertoLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelOperaciones.setBackground(new java.awt.Color(0, 51, 102));

        jTabbedPane2.setBackground(new java.awt.Color(0, 51, 51));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        Panel2.setBackground(new java.awt.Color(41, 128, 185));

        panelTablasCifrar.setBackground(new java.awt.Color(153, 204, 255));
        panelTablasCifrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 10, true));

        jSplitPane4.setDividerLocation(337);

        tableASCII1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableASCII1.setRowSelectionAllowed(false);
        tableASCII1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneASCII1.setViewportView(tableASCII1);

        jSplitPane4.setLeftComponent(scrollPaneASCII1);

        tableHex1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHex1.setRowSelectionAllowed(false);
        tableHex1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneHex1.setViewportView(tableHex1);

        jSplitPane4.setRightComponent(scrollPaneHex1);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setText("ASCII");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel10.setText("HEXADECIMAL");

        javax.swing.GroupLayout panelTablasCifrarLayout = new javax.swing.GroupLayout(panelTablasCifrar);
        panelTablasCifrar.setLayout(panelTablasCifrarLayout);
        panelTablasCifrarLayout.setHorizontalGroup(
            panelTablasCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasCifrarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(193, 193, 193))
            .addGroup(panelTablasCifrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jSplitPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTablasCifrarLayout.setVerticalGroup(
            panelTablasCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablasCifrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTablasCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelCifrar.setBackground(new java.awt.Color(153, 204, 255));
        panelCifrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 10, true));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel21.setText("Posición");

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel22.setText("ASCII:");

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel23.setText("HEX:");

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel24.setText("Contraseña");

        btnCifrar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCifrar.setForeground(new java.awt.Color(0, 0, 204));
        btnCifrar.setText("CIFRAR");
        btnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarActionPerformed(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 204, 51));
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel38.setText(" /");

        javax.swing.GroupLayout panelCifrarLayout = new javax.swing.GroupLayout(panelCifrar);
        panelCifrar.setLayout(panelCifrarLayout);
        panelCifrarLayout.setHorizontalGroup(
            panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCifrarLayout.createSequentialGroup()
                .addGroup(panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCifrarLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalBytes1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addComponent(txtAsciiValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHexValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCifrarLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCifrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Guardar)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelCifrarLayout.setVerticalGroup(
            panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(spinnerSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHexValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtTotalBytes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtAsciiValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(19, 19, 19)
                .addGroup(panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCifrar)
                        .addComponent(Guardar))))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ARCHIVO CIFRADO");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(331, 331, 331))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panelTablasCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panelCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTablasCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane2.addTab("CIFRAR", Panel2);

        Panel3.setBackground(new java.awt.Color(52, 152, 219));
        Panel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        panelDescifrado.setBackground(new java.awt.Color(153, 204, 255));
        panelDescifrado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 10, true));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel25.setText("Posición ");

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel26.setText("ASCII:");

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel27.setText("HEX:");

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel28.setText("Contraseña");

        btnDescifrar1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnDescifrar1.setForeground(new java.awt.Color(204, 0, 51));
        btnDescifrar1.setText("DESCIFRAR");
        btnDescifrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrar1ActionPerformed(evt);
            }
        });

        Guardar1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Guardar1.setForeground(new java.awt.Color(0, 204, 51));
        Guardar1.setText("GUARDAR");
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel37.setText("/");

        javax.swing.GroupLayout panelDescifradoLayout = new javax.swing.GroupLayout(panelDescifrado);
        panelDescifrado.setLayout(panelDescifradoLayout);
        panelDescifradoLayout.setHorizontalGroup(
            panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescifradoLayout.createSequentialGroup()
                .addGroup(panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescifradoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerSeleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalBytes2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDescifradoLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescifradoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnDescifrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar1))
                    .addGroup(panelDescifradoLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAsciiValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHexValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelDescifradoLayout.setVerticalGroup(
            panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescifradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25)
                    .addGroup(panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerSeleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalBytes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(txtAsciiValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(txtHexValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDescifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescifrar1)
                    .addComponent(Guardar1))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ARCHIVO DESCIFRADO");

        panelTablasDescifrar.setBackground(new java.awt.Color(153, 204, 255));
        panelTablasDescifrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 10, true));

        jSplitPaneDescifrar.setDividerLocation(337);

        tableASCII2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableASCII2.setRowSelectionAllowed(false);
        tableASCII2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneASCII2.setViewportView(tableASCII2);

        jSplitPaneDescifrar.setLeftComponent(scrollPaneASCII2);

        tableHex2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHex2.setRowSelectionAllowed(false);
        tableHex2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneHex2.setViewportView(tableHex2);

        jSplitPaneDescifrar.setRightComponent(scrollPaneHex2);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setText("ASCII");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setText("HEX");

        javax.swing.GroupLayout panelTablasDescifrarLayout = new javax.swing.GroupLayout(panelTablasDescifrar);
        panelTablasDescifrar.setLayout(panelTablasDescifrarLayout);
        panelTablasDescifrarLayout.setHorizontalGroup(
            panelTablasDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablasDescifrarLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(panelTablasDescifrarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSplitPaneDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelTablasDescifrarLayout.setVerticalGroup(
            panelTablasDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablasDescifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablasDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPaneDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTablasDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(306, 306, 306)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDescifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTablasDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDescifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("DESCIFRAR", Panel3);

        Panel4.setBackground(new java.awt.Color(0, 102, 102));

        PanelTablasHash.setBackground(new java.awt.Color(236, 240, 241));
        PanelTablasHash.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 10, true));

        jSplitPane5.setDividerLocation(337);

        tableASCII3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableASCII3.setRowSelectionAllowed(false);
        tableASCII3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneASCII3.setViewportView(tableASCII3);

        jSplitPane5.setLeftComponent(scrollPaneASCII3);

        tableHex3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHex3.setRowSelectionAllowed(false);
        tableHex3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneHex3.setViewportView(tableHex3);

        jSplitPane5.setRightComponent(scrollPaneHex3);

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel33.setText("ASCII");

        jLabel34.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel34.setText("HEXADECIMAL");

        javax.swing.GroupLayout PanelTablasHashLayout = new javax.swing.GroupLayout(PanelTablasHash);
        PanelTablasHash.setLayout(PanelTablasHashLayout);
        PanelTablasHashLayout.setHorizontalGroup(
            PanelTablasHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablasHashLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(156, 156, 156))
            .addGroup(PanelTablasHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTablasHashLayout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jSplitPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );
        PanelTablasHashLayout.setVerticalGroup(
            PanelTablasHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablasHashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTablasHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(PanelTablasHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTablasHashLayout.createSequentialGroup()
                    .addGap(0, 28, Short.MAX_VALUE)
                    .addComponent(jSplitPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );

        panelHash.setBackground(new java.awt.Color(236, 240, 241));
        panelHash.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 10, true));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel29.setText("Posición ");

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel30.setText("ASCII:");

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel31.setText("HEX:");

        jLabel32.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel32.setText("HASH");

        btnEditar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(102, 0, 204));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        CalcularHash.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        CalcularHash.setForeground(new java.awt.Color(0, 204, 51));
        CalcularHash.setText("CALCULAR");
        CalcularHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularHashActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel39.setText(" /");

        javax.swing.GroupLayout panelHashLayout = new javax.swing.GroupLayout(panelHash);
        panelHash.setLayout(panelHashLayout);
        panelHashLayout.setHorizontalGroup(
            panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHashLayout.createSequentialGroup()
                .addGroup(panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHashLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerSeleccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel39))
                    .addGroup(panelHashLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelHashLayout.createSequentialGroup()
                        .addComponent(txtTotalBytes3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addComponent(txtPassword2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHashLayout.createSequentialGroup()
                        .addComponent(txtAsciiValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHexValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar))
                    .addGroup(panelHashLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(CalcularHash)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelHashLayout.setVerticalGroup(
            panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(spinnerSeleccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHexValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtTotalBytes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtAsciiValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcularHash))
                .addContainerGap())
        );

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("HASHING");

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(PanelTablasHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(panelHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTablasHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        jTabbedPane2.addTab("HASH", Panel4);

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("OPERACIONES");

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel16))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelBitacora.setBackground(new java.awt.Color(0, 51, 102));

        txtAreaBitacora.setBackground(new java.awt.Color(204, 255, 255));
        txtAreaBitacora.setColumns(20);
        txtAreaBitacora.setRows(5);
        ScrollPaneBitacora.setViewportView(txtAreaBitacora);

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PROCEDIMIENTO");

        btnLimpiar.setBackground(new java.awt.Color(153, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR LOG.");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBitacoraLayout = new javax.swing.GroupLayout(PanelBitacora);
        PanelBitacora.setLayout(PanelBitacoraLayout);
        PanelBitacoraLayout.setHorizontalGroup(
            PanelBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBitacoraLayout.createSequentialGroup()
                .addGroup(PanelBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBitacoraLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBitacoraLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnLimpiar))
                    .addGroup(PanelBitacoraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPaneBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        PanelBitacoraLayout.setVerticalGroup(
            PanelBitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBitacoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(panelOperaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelArchivoAbierto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArchivoAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ScrollPanePrincipal.setViewportView(PanelPrincipal);

        getContentPane().add(ScrollPanePrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(); //Crea un cuadro de diálogo para seleccionar archivos.
        int resultado = fileChooser.showOpenDialog(this);//Muestra el cuadro de diálogo para abrir un archivo.
        if (resultado == JFileChooser.APPROVE_OPTION) {//Verifica si el usuario seleccionó un archivo correctamente
            // Obtener la ruta del archivo seleccionado
            archivo = fileChooser.getSelectedFile();
            ruta = archivo.getAbsolutePath();
            jTextFielddireccion.setText(ruta);//Pone la direccion del archivo en el JtextField
            abrir.procesarArchivo(archivo);//Procesa el archivo para sacar los bytes y ponerlos en arreglos bidimensionales para ascii y hexadecimal
             metodosarchivo.agregarLog(txtAreaBitacora, "NUEVO ARCHIVO ABIERTO....");
        }
        byteList = abrir.convertirAArrayList(abrir.getAsciiData()); //Obtiene la lista de bytes que fueron tomados del archivo
        totalBytes = abrir.convertirAArrayList(abrir.getAsciiData()).size();

        //byteList = abrir.getByteList(); //Obtiene la lista de bytes que fueron tomados del archivo
        //totalBytes = abrir.getTotalBytes();
        inicializarcomportamientoarchivo.setByteList(byteList); //Se ocupa para poner para que el comportamiento de ver bytes de archivo funcione
        inicializarcomportamientoarchivo.setTotalBytes(totalBytes); //Se ocupa para poner para que el comportamiento de ver bytes de archivo funcione
        abrir.setTotalBytes(abrir.getX());//Total de bytes para recorrer toda la tabla

        inicializartablas(txtTotalBytes, spinnerSeleccion, tableASCII, tableHex, abrir);//Inicializa la tabla para mostrar los archivos
    }//GEN-LAST:event_jButtonAbrirActionPerformed
    public void inicializartablas(JTextField txtTotalBytes, JSpinner spinnerSeleccion, JTable tableASCII, JTable tableHex, MostrarArchivo abrir) {//Metodo para inicializar las tablas ya sea con los bytes del archivo o con los bytes de cifrado o descifrado 

        txtTotalBytes.setText(String.valueOf(abrir.getTotalBytes()));
        // Ajustar el Spinner al rango correcto
        System.out.println("X: ->" + archivonormal.getTotalBytes());
        spinnerSeleccion.setModel(new SpinnerNumberModel(0, 0, abrir.getTotalBytes() - 1, 1));

        // Limpiar los modelos antes de insertar nuevos datos
        tableASCII.setModel(new DefaultTableModel());  // Vacía la tabla
        tableHex.setModel(new DefaultTableModel());    // Vacía la tabla

        tableASCII.setModel(new DefaultTableModel(abrir.getAsciiData(), columnNames));//Esto actualiza la tabla con nuevos datos.
        tableHex.setModel(new DefaultTableModel(abrir.getHexData(), columnNames));
    }
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        inicializarcomportamientocifrado.guardarArchivo(this, metodosarchivo.getEncryptedBytes());
    }//GEN-LAST:event_GuardarActionPerformed

    private void btnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarActionPerformed

        try {
          //  txtAreaBitacora.setText("");
            //metodosarchivo.agregarLog(txtAreaBitacora, "CIFRANDO ARCHIVO....");
    
            // Se necesita para que procese el archivo y funcione los metodos
//           archivonormal.procesarArchivo(archivo);
            //Se necesita darle la lista de bytes tomados del archivo y el total de bytes
            archivonormal.setByteList(byteList);
            
            metodosarchivo.setMensajelog(txtAreaBitacora);//Poner los mensajes 
            //Verifica que la contraseña no este vacia
            //Lee el archivo y saca los bytes de la contraseña
            //cifra con los 9 pasos 
            metodosarchivo.cifrarArchivo(ruta, txtPassword.getText(), this); //Cifra el archivo con los bytes que contiene y la contraseña
            //Devuelve la lista de bytes ya cifrados y se los da a mostrarDatosEnTablas
            //para que pueda acomodarlos en los arreglos bidimensionales que iran en las tablas correspondientes de cifrado
            archivonormal.convertirAFormatoTabla(metodosarchivo.getEncryptedBytes(), 11);
            //Le doy el arreglo de bytes ya cifrados tomados en el archivo y la longitud

            inicializarcomportamientocifrado.setByteList(archivonormal.convertirAArrayList(archivonormal.getAsciiData()));
            inicializarcomportamientocifrado.setTotalBytes(archivonormal.convertirAArrayList(archivonormal.getAsciiData()).size());

            archivonormal.setTotalBytes(archivonormal.getX());

            //inicializarcomportamientocifrado.setByteList(metodosarchivo.getEncryptedBytes());
            //inicializarcomportamientocifrado.setTotalBytes(totalBytes);
            //Le doy el objeto que ya ha sido inicializado y ya se hayan obtenido los arreglos bidimensionales
            //para que use los getters dentro de inicializar las tablas y pueda obtener los arreglos bidimensionales de los 
            //bytes cifrados y puedan mostrarse en tablas
            inicializartablas(txtTotalBytes1, spinnerSeleccion1, tableASCII1, tableHex1, archivonormal);
        } catch (IOException ex) {
            Logger.getLogger(interfaz2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCifrarActionPerformed

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        // TODO add your handling code here:
        inicializarcomportamientodescifrado.guardarArchivo(this, metodosarchivo.getBytesOriginales());
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void btnDescifrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrar1ActionPerformed
       

        //Se necesita darle la lista de bytes tomados del archivo y el total de bytes
        archivonormal.setByteList(archivonormal.convertirAArrayList(archivonormal.getAsciiData()));

        // TODO add your handling code here:
        metodosarchivo.DescifrarBytes(metodosarchivo.getEncryptedBytes(), txtPassword1.getText());
        // listatitulos
        //ArrayList<Byte> byteList
        //convertirAArrayList(ascii y hex)
        //  archivonormal.mostrarDatosEnTablas(metodosarchivo.getBytesOriginales());
        archivonormal.convertirAFormatoTabla(metodosarchivo.getDesencryptedBytes(), 11);
        //Le doy el arreglo de bytes ya cifrados tomados en el archivo y la longitud
        inicializarcomportamientodescifrado.setByteList(archivonormal.convertirAArrayList(archivonormal.getAsciiData()));//Convierte el ascii[][] a un arraylist
        inicializarcomportamientodescifrado.setTotalBytes(archivonormal.convertirAArrayList(archivonormal.getAsciiData()).size());
        //Le doy el objeto que ya ha sido inicializado y ya se hayan obtenido los arreglos bidimensionales
        //para que use los getters dentro de inicializar las tablas y pueda obtener los arreglos bidimensionales de los 
        //bytes cifrados y puedan mostrarse en tablas
        archivonormal.setTotalBytes(archivonormal.getX());//Para darle la longitud al spinner
        inicializartablas(txtTotalBytes2,
                spinnerSeleccion2,
                tableASCII2,
                tableHex2,
                archivonormal);

    }//GEN-LAST:event_btnDescifrar1ActionPerformed

    private void CalcularHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularHashActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // Se necesita para que procese el archivo y funcione los metodos
        //SIENTO QUE NO ES NECESARIO YA QUE ARRIBA YA LOS INICIALICE
        //Se necesita darle la lista de bytes tomados del archivo y el total de bytes
        //archivonormal.setByteList(byteList);
        // archivonormal.setTotalBytes(totalBytes);

        // metodosarchivo.DescifrarBytes(metodosarchivo.getEncryptedBytes(), "nada");
        //Inicializa los comportamientos de las tablas de hash no se ocupa contraseña por lo tanto nada     
        metodosarchivo.setBytesOriginales(byteList);//ByteList son la lista de bytes tomadas del archivo de texto algunos pasos de hash van a requerir que recorra todo el arraylist
        metodosarchivo.generarHashNuevo();
        ArrayList<Byte> listaBytes = new ArrayList<>(); //Vamos a convertir un arreglo de bytes a un arraylist de bytes
        byte[] arregloBytes = new byte[10];
        //RECIBO LA CADENA DE TEXTO DEL HASH PARA PASARLO A UN ARREGLO DE BYTES SUS VALORES EN ASCII
        arregloBytes = metodosarchivo.getCharHash().getBytes();//Recorro el arreglo de hash que maximo son 10 para ponerlos en la tabla
        // Recorrer el arreglo y agregar cada byte al ArrayList
        for (byte b : arregloBytes) {
            listaBytes.add(b);
        }
        archivonormalhash.convertirAFormatoTabla(listaBytes, 11);
        // archivonormalhash.setAsciiData(archivonormalhash.reemplazarValores(archivonormalhash.getAsciiData()));
        // Convertir char[] a String y concatenar
        txtPassword2.setText(metodosarchivo.getCharHash());
        inicializarcomportamientodehash.setByteList(archivonormalhash.convertirAArrayList(archivonormalhash.getAsciiData()));//Para ponerlos en textfield
        inicializarcomportamientodehash.setTotalBytes(archivonormalhash.convertirAArrayList(archivonormalhash.getAsciiData()).size());
        archivonormalhash.setTotalBytes(archivonormalhash.getX());
        // inicializarcomportamientodehash.setByteList(listaBytes);//Para ponerlos en textfield
        // inicializarcomportamientodehash.setTotalBytes(listaBytes.size());
        inicializartablas(txtTotalBytes3,
                spinnerSeleccion3,
                tableASCII3,
                tableHex3,
                archivonormalhash);

    }//GEN-LAST:event_CalcularHashActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarArchivoActionPerformed
        // TODO add your handling code here:
        inicializarcomportamientoarchivo.setAsciiData(abrir.getAsciiData());
        inicializarcomportamientoarchivo.setHexData(abrir.getHexData());
        inicializarcomportamientoarchivo.editarTablas(txtAsciiValue, txtHexValue);
        byteList = abrir.convertirAArrayList(abrir.getAsciiData());
        inicializarcomportamientoarchivo.setByteList(byteList);
        //Repintamos las tablas modificadas
        tableASCII.setModel(new DefaultTableModel(inicializarcomportamientoarchivo.getAsciiData(), columnNames));
        tableHex.setModel(new DefaultTableModel(inicializarcomportamientoarchivo.getHexData(), columnNames));
    }//GEN-LAST:event_btnEditarArchivoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtAreaBitacora.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularHash;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel PanelArchivo;
    private javax.swing.JPanel PanelBitacora;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelTablasHash;
    private javax.swing.JScrollPane ScrollPaneBitacora;
    private javax.swing.JScrollPane ScrollPanePrincipal;
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnDescifrar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarArchivo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelTables4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPaneDescifrar;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JPanel panelArchivoAbierto;
    private javax.swing.JPanel panelArchivoOriginal;
    private javax.swing.JPanel panelCifrar;
    private javax.swing.JPanel panelDescifrado;
    private javax.swing.JPanel panelHash;
    private javax.swing.JPanel panelOperaciones;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JPanel panelTablasCifrar;
    private javax.swing.JPanel panelTablasDescifrar;
    private javax.swing.JScrollPane scrollPaneASCII;
    private javax.swing.JScrollPane scrollPaneASCII1;
    private javax.swing.JScrollPane scrollPaneASCII2;
    private javax.swing.JScrollPane scrollPaneASCII3;
    private javax.swing.JScrollPane scrollPaneHex;
    private javax.swing.JScrollPane scrollPaneHex1;
    private javax.swing.JScrollPane scrollPaneHex2;
    private javax.swing.JScrollPane scrollPaneHex3;
    private javax.swing.JSpinner spinnerSeleccion;
    private javax.swing.JSpinner spinnerSeleccion1;
    private javax.swing.JSpinner spinnerSeleccion2;
    private javax.swing.JSpinner spinnerSeleccion3;
    private javax.swing.JTable tableASCII;
    private javax.swing.JTable tableASCII1;
    private javax.swing.JTable tableASCII2;
    private javax.swing.JTable tableASCII3;
    private javax.swing.JTable tableHex;
    private javax.swing.JTable tableHex1;
    private javax.swing.JTable tableHex2;
    private javax.swing.JTable tableHex3;
    private javax.swing.JTextArea txtAreaBitacora;
    private javax.swing.JTextField txtAsciiValue;
    private javax.swing.JTextField txtAsciiValue1;
    private javax.swing.JTextField txtAsciiValue2;
    private javax.swing.JTextField txtAsciiValue3;
    private javax.swing.JTextField txtHexValue;
    private javax.swing.JTextField txtHexValue1;
    private javax.swing.JTextField txtHexValue2;
    private javax.swing.JTextField txtHexValue3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPassword2;
    private javax.swing.JTextField txtTotalBytes;
    private javax.swing.JTextField txtTotalBytes1;
    private javax.swing.JTextField txtTotalBytes2;
    private javax.swing.JTextField txtTotalBytes3;
    // End of variables declaration//GEN-END:variables
}
