/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cifrado;

/**
 *
 * @author cris_
 */
public class Tablas extends javax.swing.JFrame {

    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalTablas = new javax.swing.JPanel();
        PanelArchivo = new javax.swing.JPanel();
        txtArchivo = new javax.swing.JLabel();
        jTextFielddireccion = new javax.swing.JTextField();
        jButtonAbrir = new javax.swing.JButton();
        PanelTablas = new javax.swing.JPanel();
        SubPanelTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        SubPanelDeTablas = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        scrollPaneASCII = new javax.swing.JScrollPane();
        tableASCII = new javax.swing.JTable();
        scrollPaneHex = new javax.swing.JScrollPane();
        tableHex = new javax.swing.JTable();
        SubPanelValores = new javax.swing.JPanel();
        txtPosicion = new javax.swing.JLabel();
        spinnerSeleccion = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtTotalBytes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAsciiValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHexValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipalTablas.setBackground(new java.awt.Color(51, 51, 255));

        PanelArchivo.setBackground(new java.awt.Color(102, 102, 255));
        PanelArchivo.setLayout(new javax.swing.BoxLayout(PanelArchivo, javax.swing.BoxLayout.LINE_AXIS));

        txtArchivo.setText("ARCHIVO");
        PanelArchivo.add(txtArchivo);
        PanelArchivo.add(jTextFielddireccion);

        jButtonAbrir.setText("ABRIR");
        PanelArchivo.add(jButtonAbrir);

        PanelTablas.setBackground(new java.awt.Color(204, 255, 255));
        PanelTablas.setLayout(new javax.swing.BoxLayout(PanelTablas, javax.swing.BoxLayout.Y_AXIS));

        SubPanelTitulo.setBackground(new java.awt.Color(204, 204, 255));

        txtTitulo.setText("ARCHIVO ORIGINAL");
        SubPanelTitulo.add(txtTitulo);

        PanelTablas.add(SubPanelTitulo);

        SubPanelDeTablas.setBackground(new java.awt.Color(204, 204, 255));
        SubPanelDeTablas.setLayout(new java.awt.GridLayout());

        tableASCII.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneASCII.setViewportView(tableASCII);

        jSplitPane2.setLeftComponent(scrollPaneASCII);

        tableHex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneHex.setViewportView(tableHex);

        jSplitPane2.setRightComponent(scrollPaneHex);

        SubPanelDeTablas.add(jSplitPane2);

        PanelTablas.add(SubPanelDeTablas);

        SubPanelValores.setBackground(new java.awt.Color(204, 204, 255));

        txtPosicion.setText("POSICION");
        SubPanelValores.add(txtPosicion);

        spinnerSeleccion.setMinimumSize(new java.awt.Dimension(100, 22));
        spinnerSeleccion.setPreferredSize(new java.awt.Dimension(100, 50));
        SubPanelValores.add(spinnerSeleccion);

        jLabel4.setText("/");
        SubPanelValores.add(jLabel4);

        txtTotalBytes.setMinimumSize(new java.awt.Dimension(128, 22));
        txtTotalBytes.setPreferredSize(new java.awt.Dimension(128, 50));
        SubPanelValores.add(txtTotalBytes);

        jLabel5.setText("ASCII:");
        SubPanelValores.add(jLabel5);

        txtAsciiValue.setMinimumSize(new java.awt.Dimension(128, 22));
        txtAsciiValue.setPreferredSize(new java.awt.Dimension(128, 50));
        SubPanelValores.add(txtAsciiValue);

        jLabel6.setText("HEX:");
        SubPanelValores.add(jLabel6);

        txtHexValue.setMinimumSize(new java.awt.Dimension(128, 100));
        txtHexValue.setPreferredSize(new java.awt.Dimension(128, 50));
        SubPanelValores.add(txtHexValue);

        PanelTablas.add(SubPanelValores);

        javax.swing.GroupLayout PanelPrincipalTablasLayout = new javax.swing.GroupLayout(PanelPrincipalTablas);
        PanelPrincipalTablas.setLayout(PanelPrincipalTablasLayout);
        PanelPrincipalTablasLayout.setHorizontalGroup(
            PanelPrincipalTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPrincipalTablasLayout.setVerticalGroup(
            PanelPrincipalTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelArchivo;
    private javax.swing.JPanel PanelPrincipalTablas;
    private javax.swing.JPanel PanelTablas;
    private javax.swing.JPanel SubPanelDeTablas;
    private javax.swing.JPanel SubPanelTitulo;
    private javax.swing.JPanel SubPanelValores;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JScrollPane scrollPaneASCII;
    private javax.swing.JScrollPane scrollPaneHex;
    private javax.swing.JSpinner spinnerSeleccion;
    private javax.swing.JTable tableASCII;
    private javax.swing.JTable tableHex;
    private javax.swing.JLabel txtArchivo;
    private javax.swing.JTextField txtAsciiValue;
    private javax.swing.JTextField txtHexValue;
    private javax.swing.JLabel txtPosicion;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtTotalBytes;
    // End of variables declaration//GEN-END:variables
}
